services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_DATABASE_NAME}
      POSTGRES_USER: ${RESOURCE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${RESOURCE_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"  # Maps container port 5432 to host port 5432
    networks:
      - resource-network      
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SONG_DATABASE_NAME}
      POSTGRES_USER: ${SONG_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SONG_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"  # Maps container port 5432 to host port 5433 (to avoid conflict)
    networks:
      - song-network      
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql      

  resource-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    image: resource-service:1.0
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DATASOURCE_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    networks:
      - resource-network
      - resource-song-network
      - eureka-server-network
    depends_on:
      - resource-db
      - song-service

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    image: song-service:1.0
    deploy:
        replicas: 2
    ports:
      - "8082-8083:8082"
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DATASOURCE_PASSWORD}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    networks:
      - song-network
      - resource-song-network
      - eureka-server-network
    depends_on:
      - song-db

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:1.0
    ports:
      - "8761:8761"
    networks:
      - eureka-server-network

networks:
  resource-network:
    name: resource-network
    driver: bridge  
  song-network:
    name: song-network
    driver: bridge 
  resource-song-network:
    name: resource-song-network
    driver: bridge
  eureka-server-network:
    name: eureka-server
    driver: bridge


# Related settings for application.properties:
# 
# For resource-service:
# spring.datasource.url=jdbc:postgresql://localhost:5432/resource-db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
#
# For song-service:
# spring.datasource.url=jdbc:postgresql://localhost:5433/song-db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
