server.port=${SERVER_PORT:8082}
spring.application.name=song-service

# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka Server Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
# How often this instance sends heartbeats to Eureka
eureka.instance.lease-renewal-interval-in-seconds=20
# How long Eureka waits before removing an instance that stopped sending heartbeats
eureka.instance.lease-expiration-duration-in-seconds=30

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always