spring:
  application:
    name: eureka-server
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # Frequency of registry data retrieval from the server to the client's local cache
    registry-fetch-interval-seconds: 5
  instance:
    # Frequency of heartbeats sent by the client to the server
    lease-renewal-interval-in-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
