package com.microservice.resource.repository;

import com.microservice.resource.entity.Resource;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration test for ResourceRepository against a real PostgreSQL database.
 *
 * HOW TO RUN:
 *   mvn test -pl resource-service -Dtest=ResourceRepositoryIT
 *   Requires Docker to be running on the host machine.
 */
@Testcontainers
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@DirtiesContext
class ResourceRepositoryIT {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:17-alpine");

    @DynamicPropertySource
    static void datasourceProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
    }

    @Autowired
    private ResourceRepository repository;

    @Test
    void save_newResource_assignsAutoGeneratedId() {
        Resource resource = new Resource("songs/1_track.mp3");

        Resource saved = repository.save(resource);

        assertThat(saved.getId()).isGreaterThan(0);
    }

    @Test
    void save_twoResources_assignsUniqueIds() {
        Resource r1 = repository.save(new Resource("songs/1_a.mp3"));
        Resource r2 = repository.save(new Resource("songs/2_b.mp3"));

        assertThat(r1.getId()).isNotEqualTo(r2.getId());
    }

    @Test
    void findById_savedResource_returnsCorrectFileLocation() {
        Resource saved = repository.save(new Resource("songs/3_track.mp3"));

        Optional<Resource> found = repository.findById(saved.getId());

        assertThat(found).isPresent();
        assertThat(found.get().getFileLocation()).isEqualTo("songs/3_track.mp3");
    }

    @Test
    void existsById_savedResource_returnsTrue() {
        Resource saved = repository.save(new Resource("songs/4_track.mp3"));

        assertThat(repository.existsById(saved.getId())).isTrue();
    }

    @Test
    void existsById_nonExistentId_returnsFalse() {
        assertThat(repository.existsById(99999)).isFalse();
    }

    @Test
    void deleteById_savedResource_removesFromDatabase() {
        Resource saved = repository.save(new Resource("songs/5_track.mp3"));
        int id = saved.getId();

        repository.deleteById(id);

        assertThat(repository.existsById(id)).isFalse();
    }

    @Test
    void save_updatesFileLocation_persistsChange() {
        Resource resource = repository.save(new Resource(""));
        resource.setFileLocation("songs/" + resource.getId() + "_updated.mp3");

        resource = repository.save(resource);

        assertThat(repository.findById(resource.getId()).get().getFileLocation())
                .isEqualTo("songs/" + resource.getId() + "_updated.mp3");
    }
}
