server.port=${SERVER_PORT:8888}
spring.application.name=config-server

spring.cloud.config.server.git.uri=${CONFIG_REPO_URI:file:///config-repo}
spring.cloud.config.server.git.default-label=microservices_fundamentals_service_discovery
spring.cloud.config.server.git.clone-on-start=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

management.endpoints.web.exposure.include=health,env
management.endpoint.health.show-details=always